# Generated by Django 3.2.9 on 2021-12-16 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='task',
        ),
        migrations.CreateModel(
            name='Sub_Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
