# Generated by Django 3.2.9 on 2021-12-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20211216_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_task',
            old_name='parent_task',
            new_name='sub_task',
        ),
        migrations.AddField(
            model_name='sub_task',
            name='task',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sub_task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=250),
        ),
    ]
