# Generated by Django 3.2.9 on 2021-12-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20211216_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_task',
            name='task',
        ),
    ]
