# Generated by Django 3.2.9 on 2021-12-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_sub_task_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_task',
            old_name='sub_task',
            new_name='parent_task',
        ),
    ]
