# Generated by Django 3.2.9 on 2021-12-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_rename_sub_task_sub_task_parent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_task',
            name='sub_task_name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='sub_task',
            name='parent_task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
