# Generated by Django 3.2.9 on 2021-12-16 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20211216_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_task',
            name='parent_task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
        migrations.AlterField(
            model_name='sub_task',
            name='sub_task_name',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
