# Generated by Django 3.2.9 on 2021-12-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_sub_task_sub_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
