# Generated by Django 3.2.9 on 2021-12-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20211216_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_task',
            name='deadline',
            field=models.IntegerField(blank=True, null=True, unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.FloatField(blank=True, null=True, unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(default=False),
        ),
    ]
