# Generated by Django 3.2.9 on 2021-12-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_task',
            name='deadline',
            field=models.IntegerField(help_text='Min', null=True, unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.IntegerField(help_text='Min', null=True, unique_for_date=True),
        ),
    ]
